server:
  port:
    9090

spring:
  application:
    name: multiple_databases

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/mydatabase
      username: abhishek
      password: sarasu10
      driver-class-name: com.mysql.cj.jdbc.Driver

    oraclesql:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: abhishek
      password: sarasu10
      driver-class-name: oracle.jdbc.driver.OracleDriver
