spring:
  application:
    name: schedular_app

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: abhishek
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver

jpa:
  hibernate:
    ddl-auto: update #create #create-drop
  show-sql: true

server:
  port: 9099