spring:
  application:
    name: ocr_task_bank_statement

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/mydatabase
      username: abhishek
      password: sarasu10
      driver-class-name: com.mysql.cj.jdbc.Driver

    oracle:
      url: jdbc:oracle:thin:@localhost:1521/xe
      username: abhishek
      password: sarasu10
      driver-class-name: oracle.jdbc.OracleDriver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

server:
  port: 9096